### ISSUE TITLE
Testnet issues?

### ISSUE THREAD

**Issue by ounkeo** [stellarguard/stellarguard-issues#1]
Hi,

Thanks for this awesome tool.  The authenticator 2fa and emails work as expected.
On the testnet, when I try to enter the Authenticator Code, I get an error "An unknown error has occurred. Please try again later."

XDR AAAAAG+i3v+FAAIt+5A5HAEXnV0196Rith3+LoPRSuHM6ZzMAAAAZAB4sdwAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAADHRlc3RuZXQgNC0+MwAAAAEAAAABAAAAAG+i3v+FAAIt+5A5HAEXnV0196Rith3+LoPRSuHM6ZzMAAAAAQAAAAC1B6DnlwxASTa/jMSG7i3v5l1rnsHZXh2C1RbAGb0AtwAAAAAAAAAL6fg8gAAAAAAAAAABzOmczAAAAECaWvhXZgW6VLQr68KLyOXAiIpxz+yC5uZqf11yXsFi/dnIuThAFTuqjcOpNzduHPA982hEsjSL/HSPSvqD34sH

edit: Stellar testnet seems to not currently be working sending tx from acct A to acct B disregarding stellarguard. I'm using their stellar laboratory, tx builder, tx signer, post tx.

**Comment by pselden** [comment]
Thanks for the report, apologies for not seeing it earlier.

Is this still an issue? I've just added the ability to view the result of a failed transaction (as long as it fails due to a Stellar failure and not some internal issue).

I have a hunch you may have run into an issue that hit a lot of people on the testnet where friendbot funding was reporting success but actually was silently failing, and thus trying to send to an account that hadn't been created yet. If not, maybe this new addition will help track things down further.

![screen shot 2018-03-21 at 1 45 30 am](https://user-images.githubusercontent.com/709282/37695987-b3a675d4-2ca9-11e8-80da-4352fcabd1a3.png)

**Comment by pselden** [comment]
Note: I've only added this to the test version right now. Will be released to production in a few days.

**Comment by pselden** [comment]
Added to production now.
